version: '3.8'

services:
  webcrawler:
    build:
      context: .
      dockerfile: Dockerfile
    image: junghyunmoon/webcrawler:latest
    env_file:
      - .env
    environment:
      USER_ID: ${USER_ID}
      USER_PW: ${USER_PW}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      UPSTAGE_API_KEY: ${UPSTAGE_API_KEY}
    volumes:
      - .:/app
    command: python crawler/wiki.py
