services:
  webcrawler:
    build:
      context: ../
      dockerfile: docker/dockerfile
    image: junghyunmoon/webcrawler:latest
    env_file:
      - .env
    environment:
      USER_ID: ${USER_ID}
      USER_PW: ${USER_PW}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      UPSTAGE_API_KEY: ${UPSTAGE_API_KEY}
    volumes:
      - ./crawler:/app/crawler
      - ./logs:/app/logs
      - ./data:/app/data